# Generated by Django 5.0.2 on 2024-03-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodItems', '0003_fooditems_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='selectfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('foodtype', models.CharField(max_length=10)),
                ('pdf', models.FileField(upload_to='items')),
            ],
        ),
    ]
