# Generated by Django 5.0.2 on 2024-03-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodItems', '0004_selectfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='selectfile',
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='image',
            field=models.FileField(upload_to='fooditems'),
        ),
    ]
