# Generated by Django 5.0.2 on 2024-03-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodItems', '0005_delete_selectfile_alter_fooditems_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='Recipe',
            field=models.FileField(default=1, upload_to='fooditems'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='image',
            field=models.ImageField(upload_to='fooditems'),
        ),
    ]
