# Generated by Django 5.0.2 on 2024-03-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_student_age_alter_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phNo',
            field=models.IntegerField(default=77319),
            preserve_default=False,
        ),
    ]
