# Generated by Django 5.0.2 on 2024-03-14 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_student_phno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phNo',
        ),
    ]
