# Generated by Django 5.0.2 on 2024-03-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_student_phno'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('foodtype', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
